zuora_client: dev
port: 9054
zuora_max_retries: 10
notification_queue_size: 20

zuora_clients:
  dev:
    wsdl: zuora.a.81.0.wsdl.xml
    username: api.test@economist.com
    password: CXYOfpmSkrD63e6AZ
    accesspoint: https://apisandbox.zuora.com/
    rest_accesspoint: https://apisandbox-api.zuora.com/rest/v1/
    ssl: true
  test:
    wsdl: zuora.a.81.0.wsdl.xml
    username: claude.gibert+api1@datasift.com
    password: CXYOfpmSkrD63e6SB
    accesspoint: https://apisandbox.zuora.com/
    rest_accesspoint: https://apisandbox-api.zuora.com/rest/v1/
    ssl: true

logging:
  version: 1
  disable_existing_loggers: False
  formatters: 
    simple:
      format: "%(asctime)5s - %(name)s - %(levelname)s - %(message)s"
    advanced:
      format: "%(levelname)s %(asctime)5s %(name)s %(filename)s %(funcName)s %(lineno)d %(message)s"
  handlers:
    console_out:
      class: logging.StreamHandler
      level: ERROR
      formatter: simple
      stream: ext://sys.stdout
    console_err:
      class: logging.StreamHandler
      level: ERROR
      formatter: simple
      stream: ext://sys.stderr
    info_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: INFO            
      formatter: simple
      filename: info.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8
    error_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: ERROR            
      formatter: advanced
      filename: errors.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8
  loggers:
    my_module:
      level: ERROR
      handlers: [console_out]
      propagate: no
  root:
    level: INFO
    handlers: [console_out, console_err, info_file_handler, error_file_handler]
